"""Pure-Python T4 data contracts shared by assets and conversion tools."""

T4_JOINT_NAMES: tuple[str, ...] = (
    "J_arm_l_01",
    "J_arm_l_02",
    "J_arm_l_03",
    "J_arm_l_04",
    "J_arm_l_05",
    "J_arm_l_06",
    "J_arm_l_07",
    "J_arm_r_01",
    "J_arm_r_02",
    "J_arm_r_03",
    "J_arm_r_04",
    "J_arm_r_05",
    "J_arm_r_06",
    "J_arm_r_07",
    "J_waist_yaw",
    "J_hip_l_pitch",
    "J_hip_l_roll",
    "J_hip_l_yaw",
    "J_knee_l_pitch",
    "J_ankle_l_pitch",
    "J_ankle_l_roll",
    "J_hip_r_pitch",
    "J_hip_r_roll",
    "J_hip_r_yaw",
    "J_knee_r_pitch",
    "J_ankle_r_pitch",
    "J_ankle_r_roll",
)
